src/main/resources/application-noauth.yml
You may have noticed this during startup when using the noauth profile:
```
Using generated security password: ce94e883-c627-484b-a022-f613ce822861
This generated password is for development use only. Your security configuration must be updated before running your application in production.
```
It's not really harmful, but not useful either
=> prevent creation of default user in noauth profile too

src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java, src/main/java/ca/on/oicr/gsi/dimsum/controller/NotFoundException.java, src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/MvcUtils.java, src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/ProjectController.java, src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/CaseRestController.java, src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/RequisitionRestController.java, src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/SampleRestController.java, src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/request/DataQuery.java, src/main/java/ca/on/oicr/gsi/dimsum/data/Case.java, src/main/java/ca/on/oicr/gsi/dimsum/data/Requisition.java, src/main/java/ca/on/oicr/gsi/dimsum/data/Sample.java, src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/RequisitionSort.java, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/SampleSort.java, src/main/resources/static/css/output.css, src/main/resources/templates/detail.html, src/main/resources/templates/layout.html, src/test/java/ca/on/oicr/gsi/dimsum/service/CaseServiceTest.java, ts/data/case.ts, ts/data/qc-status.ts, ts/data/requisition.ts, ts/data/sample.ts, ts/details.ts, ts/util/html-utils.ts, ts/util/requests.ts, ts/util/table-builder.ts, ts/util/urls.ts, webpack.config.js
Will create separate tickets for filling in the missing columns (mostly metrics), and filtering tables besides the cases table.
I changed the default page size to 10 items to reduce the scrolling needed to get to other tables. @Arcslogger suggested changing this to a tabbed interface so only one table is visible at a time, which I think would be a huge improvement. We'll discuss this with users at the next meeting
=> [GLT-3687] added Project Details page

src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java, src/main/java/ca/on/oicr/gsi/dimsum/data/Test.java, src/test/resources/testdata/cases.json, ts/data/case.ts
Should not be merged until the required qc-gate-etl change goes into production: https://bitbucket.oicr.on.ca/projects/GSI/repos/qc-gate-etl/pull-requests/39/overview
=> [GLT-3718] show skipped QC gates as N/A

ts/util/html-utils.ts
Another minor space optimization (mainly for the Receipt/Inspection column)
=> allow word break on slash in table headings

ts/data/case.ts, ts/util/html-utils.ts
Add tool tips for identifying non-intuitive text fields (group ids, external names, etc.). As per [GLT-3757](https://jira.oicr.on.ca/browse/GLT-3757).
=> [GLT-3757] Identify text fields

ts/component/dropdown.ts, ts/component/table-builder.ts, ts/component/text-input.ts, ts/util/html-utils.ts
As per [GLT-3744](https://jira.oicr.on.ca/browse/GLT-3744)
Because most of the dropdown menu buttons employ the same parent class, an extra param (displayTemporary) was added in order to specify whether a button should be removed if an event calls for it, or if they are "permanent" buttons. E.g. The "Items per page" would be a permanent button (should not be removed by hitting esc or clicking out), but buttons created from selecting a filter option are temporary (can be removed by hitting esc or clicking out).
=> [GLT-3744] Add escape option for filters

src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/NotificationSort.java, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/RunSort.java
Run completion date is null when the run is still running. `Comparator.comparing` doesn't handle nulls
=> [GLT-3793] fixed NullPointerException sorting by run completion date

changes/change_supplementalSamples.md, src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java, src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/RequisitionController.java, src/main/java/ca/on/oicr/gsi/dimsum/data/Case.java, src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/PendingState.java, src/test/java/ca/on/oicr/gsi/dimsum/service/CaseServiceTest.java, src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterTest.java, src/test/resources/testdata/cases.json, ts/data/case.ts
There is really nothing to do with supplemental samples here, except that cases now belong to a single requisition instead of multiple
=> [GLT-3852] updated to support gsi-qc-etl changes for supplemental samples

changes/change_caseStartDate.md, src/main/java/ca/on/oicr/gsi/dimsum/data/Case.java
It's now possible for cases to be _only_ tissue type "R," so the old start date calculation doesn't work anymore. Now that cases have a primary requisition, this method makes more sense anyway
=> [GLT-3866] fix determining case start date

changes/add_copyName-donor, ts/data/case.ts, ts/util/html-utils.ts
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3976
✅  Includes a change file
=> [GLT-3976] added copy buttons for donor names and external names

changes/change_topButton, ts/component/table-builder.ts
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3991
✅ Includes a change file
=> [GLT-3991] add action buttons to the top

changes/fix_updateNotifications.md, src/main/java/ca/on/oicr/gsi/dimsum/service/NotificationManager.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4032
=> [GLT-4032] fixed error updating notifications

changes/change_stopped_release.md, changes/fix_stopped_overdue.md, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseSort.java, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CompletedGate.java, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/PendingState.java, src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseSortTest.java, ts/data/case.ts
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4060
=> [GLT-4060] require release for stopped cases

changes/add_GLT-4047, ts/component/table-builder.ts
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4047
=> [GLT-4047] added multi select

.vscode/launch.json, changes/add_deliverableTypeFilters.md, changes/fix_pendingWork_previousSkipped.md, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CompletedGate.java, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/PendingState.java, src/main/java/ca/on/oicr/gsi/dimsum/util/SampleUtils.java, src/test/java/ca/on/oicr/gsi/dimsum/MockCase.java, src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterTest.java, src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseSortTest.java, src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/SampleSortTest.java, ts/data/case.ts
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4051
Note the PR target is the other deliverables branch that is approved but not yet merged, and depends on Cardea changes that are also not yet merged/released
=> [GLT-4051] added deliverable-type-specific filter options

.github/workflows/ci.yml, .npmrc, README.md, package-lock.json, package.json
The `lockFileVersion` keeps changing with people using different versions of npm, and this will prevent that.
=> enforce node and npm versions

changes/fix_allDeliverableFilters.md, changes/fix_deliverableReleaseApprovalFilters.md, src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/PendingState.java, src/test/java/ca/on/oicr/gsi/dimsum/MockCase.java, src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterTest.java
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4100
=> [GLT-4100] fixed pending release approval and release filters

changes/fix_highlight.md, ts/data/case.ts
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4121
=> [GLT-4121] fixed highlighting of run-libraries that failed via run QC

changes/change_case_qc_stopped.md, ts/case-report.ts
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4252
=> [GLT-4252] Case QC Report improvements for stopped cases

changes/add_GLT-4245, changes/fix_GLT-4245, src/main/resources/static/css/output.css, src/main/resources/templates/tat-trend.html, ts/component/legend.ts, ts/component/table-builder.ts, ts/tat-trend.ts, ts/util/color-mapping.ts
=> [GLT-4245] TAT trend report legend for Color by Gate

changes/add_GLT-4261, src/main/resources/templates/tat-trend.html, ts/component/table-builder.ts, ts/tat-trend.ts, ts/util/html-utils.ts
=> [GLT-4261] TAT trend report table metrics

README.md, src/main/java/ca/on/oicr/gsi/dimsum/SecurityConfiguration.java, src/main/resources/application.yml
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4314
This would probably work with our current production IdP, but there's no good way to test that and no advantage to merging it into main right now anyway. We're going to need a branch for external-dimsum at least until we're ready to switch over to Keycloak and role-based access, so I've started the `dimsum-external` branch for that.
If you'd like to test using keycloak-dev, let me know and I can help you set it up. You'll need a login for keycloak-dev with realm admin permissions, and you'll have to run Dimsum on a URL besides "http://localhost:8081" since I am using that. This doesn't need to be a URL that's visible to Keycloak, so localhost works with a different port, or you can create yourself an alias in …
=> [GLT-4314] Simplified SAML2 internal configuration

changes/add_external_projList.md, src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/common/CommonAutocompleteRestController.java, src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/external/ExternalProjectRestController.java, src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/internal/AutocompleteRestController.java, src/main/java/ca/on/oicr/gsi/dimsum/data/external/ExternalProjectSummary.java, src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java, ts/util/urls.ts
Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4321
=> [GLT-4321] adapted Projects list page for external users
