.github/workflows/ci.yml
README.md
pom.xml

[GLT-3681] added CI via GitHub Actions

---

example-application.properties
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/CommonModelAttributeProvider.java
src/main/resources/static/css/output.css
src/main/resources/templates/layout.html
src/test/resources/application-test.properties

can be found as `jira.link`, currently blank as we don't have a full URL

[GLT-3698] added JIRA link property for bug reports

---

src/main/resources/static/css/output.css
src/main/resources/templates/layout.html
src/main/resources/templates/login.html
tailwind.config.js

navigate to /login to view changes

[GLT-3699] added login page

---

.vscode/settings.json
src/main/resources/templates/test.html
ts/common.ts
ts/data/case.ts
ts/test.ts
ts/util/table-builder.ts

Can try it out on the `/test` page. I kept it minimal for now so we can work on it in smaller pieces. I'll create separate tickets for all of these:
* add table styling
* allow selection
* fetch data from server (should do while adding the REST API)
* add paging controls
* add filtering controls
* add table actions (buttons)
* hide columns that are N/A for all rows
* add row and cell highlighting

[GLT-3706] added frontend table builder

---

src/main/resources/static/css/output.css
src/main/resources/templates/layout.html
ts/util/html-utils.ts

white space outside of the header logo is no longer a clickable link hot spot

styling fixups

---

ts/data/case.ts
ts/util/html-utils.ts
ts/util/table-builder.ts

We may or may not want to change this to record the user's choice at some point, but for now it'll just reset to the default on page load, but not when changing filters, etc.
Styling not included in this PR; will be fixed up later

[GLT-3720] added sorting controls to table builder

---

example-application.properties
src/main/java/ca/on/oicr/gsi/dimsum/FrontEndConfig.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/SiteConfigController.java
src/main/resources/templates/layout.html
src/test/resources/application-test.properties
ts/data/case.ts
ts/util/site-config.ts
ts/util/urls.ts

There are more MISO and Dashi links that we'll need later on. I just added a few as examples

[GLT-3721] added config for MISO and Dashi URLs

---

src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/MvcUtils.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/CaseRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/request/DataQuery.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/request/KeyValuePair.java
src/main/resources/static/css/output.css
ts/data/case.ts
ts/util/dropdown.ts
ts/util/table-builder.ts

text-field filtering controls will be implemented in a separate PR

[GLT-3711] Added dropdown filter controls

---

src/main/java/ca/on/oicr/gsi/dimsum/SecurityConfiguration.java

Only the `RelyingPartyRegistrationRepository` bean has changed. The rest is just the formatter that hadn't been run on this file before

[GLT-3733] fix SAML to use configured base URL for all URLs

---

.vscode/eclipse-java-google-style.xml
src/main/java/ca/on/oicr/gsi/dimsum/SecurityConfiguration.java

@mlaszloffy noticed these files were causing some weirdness with authentication, but these shouldn't require authentication anyway

removed authentication requirement from static libs

---

src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/CaseController.java
src/main/java/ca/on/oicr/gsi/dimsum/data/Case.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java
src/test/resources/testdata/cases.json
ts/data/case.ts
ts/util/urls.ts

Requires qc-gate-etl update in https://bitbucket.oicr.on.ca/projects/GSI/repos/qc-gate-etl/pull-requests/40/overview

[GLT-3689] added case details page

---

src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/AutocompleteRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/data/CaseData.java
src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java
src/main/resources/static/css/output.css
ts/data/case.ts
ts/util/dropdown.ts
ts/util/requests.ts
ts/util/table-builder.ts
ts/util/text-input.ts
ts/util/urls.ts

also removed case sensitivity in the text input filters

[GLT-3739] added autocomplete to text input filters

---

src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java
src/main/java/ca/on/oicr/gsi/dimsum/data/Lane.java
src/main/java/ca/on/oicr/gsi/dimsum/data/Run.java
src/test/resources/testdata/runs.json
ts/data/case.ts
ts/data/sample.ts

This is ready for review. Created as draft as a reminder that this depends on qc-gate-etl changes and shouldn't be merged until after that is released: https://bitbucket.oicr.on.ca/projects/GSI/repos/qc-gate-etl/pull-requests/43/overview

[GLT-3750] added metric columns from Run Scanner

---

ts/data/requisition.ts

Added missing requisition links to the informatics reviews, draft reports, and final reports table. As per [GLT-3758](https://jira.oicr.on.ca/browse/GLT-3758)

[GLT-3758] add missing requisition links

---

src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java
src/main/java/ca/on/oicr/gsi/dimsum/data/Requisition.java
src/main/java/ca/on/oicr/gsi/dimsum/data/RequisitionQcGroup.java
src/test/java/ca/on/oicr/gsi/dimsum/CaseLoaderTest.java
src/test/resources/testdata/requisitions.json
ts/data/requisition.ts
ts/data/sample.ts
ts/util/metrics.ts

Ready for review, but before merging
* qc-gate-etl update should be merged and released: https://bitbucket.oicr.on.ca/projects/GSI/repos/qc-gate-etl/pull-requests/44/overview
* tests need updated/fixed

[GLT-3761] added informatics metrics

---

ts/component/dropdown.ts
ts/util/html-utils.ts

As per [GLT-3736](https://jira.oicr.on.ca/browse/GLT-3736)

[GLT-3736] Add icon for dropdown menus

---

src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java
src/main/java/ca/on/oicr/gsi/dimsum/data/Sample.java
ts/data/case.ts
ts/data/sample.ts

As per [GLT-3762](https://jira.oicr.on.ca/browse/GLT-3762)

[GLT-3762] Show run-library lane number

---

ts/data/sample.ts
ts/run.ts

As per [GLT-3778](https://jira.oicr.on.ca/browse/GLT-3778)

[GLT-3778] Show Run-Library Lane Number on Run Details Page

---

src/main/resources/static/css/output.css
ts/component/table-builder.ts
ts/data/case.ts
ts/data/notification.ts
ts/data/requisition.ts
ts/data/sample.ts
ts/util/html-utils.ts

The legend is now added to all existing tables as a static action. There are no bulk actions yet, but this will soon be used for the "QC in MISO" button, and other features in the future

[GLT-3712] table actions

---

package-lock.json
src/main/resources/static/css/output.css
ts/component/dialog.ts
ts/component/table-builder.ts
ts/data/sample.ts
ts/util/metrics.ts
ts/util/urls.ts
tsconfig.json

This PR is only for the GLT-3782 commit. The others are in another PR, and I will rebase this branch after that gets merged.
Some of the functions in `sample.ts` were unintentionally scoped inside of another function, and fixing that made the diff pretty ugly. You can hide the whitespace changes to make your review a little easier. Either click the gear icon at the top of the diff and select "Hide whitespace," or add `?w=1` to the URL to do this.

[GLT-3782] added 'QC in MISO' button

---

.github/workflows/ci.yml
package.json

(Maven is configured to run the npm build script)

automatically run npm install via Maven

---

changes/fix_hideNaColumns.md
ts/data/sample.ts

Most of this is auto-formatting; hide whitespace changes for easier review.

[GLT-3828] hide columns that are n/a for all samples

---

changes/add_caseQcReport.md
package-lock.json
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/CaseController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/CaseRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java
src/main/resources/static/css/input.css
src/main/resources/static/css/output.css
src/main/resources/templates/case-report.html
src/main/resources/templates/detail.html
src/main/resources/templates/layout.html
src/main/resources/templates/project-detail.html
ts/case-report.ts
ts/component/attribute-list.ts
ts/component/dialog.ts
ts/component/table-builder.ts
ts/data/qc-status.ts
ts/data/requisition.ts
ts/data/sample.ts
ts/details.ts
ts/util/html-utils.ts
ts/util/metrics.ts
ts/util/requests.ts
ts/util/urls.ts
webpack.config.js

Made a separate ticket to address the requisition QC group donor ID TODOs (https://jira.oicr.on.ca/browse/GLT-3888). Not important for clinical requisitions, which this is mainly intended for, but there could be some weirdness with RUO requisitions (of which there are still none in Dimsum anyway)

[GLT-3877] added Case QC Report page

---

changes/fix_nullTimestamps
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseSort.java
ts/data/case.ts

Shouldn't happen anymore after the MISO update to prevent ghost samples in requisitions, but this will handle it anyway

[GLT-3896] handle undetermined case start/update times

---

changes/change_userManual_cases.md
changes/fix_docLinks.md
docs/index.md
docs/user_manual/cases.md
docs/user_manual/details.md
docs/user_manual/features.md
docs/user_manual/guides/review_data_entry.md
docs/user_manual/guides/review_sign_offs.md
docs/user_manual/guides/sign_off_run.md
docs/user_manual/notifications.md
docs/user_manual/omissions.md
docs/user_manual/projects.md
docs/user_manual/qc_dashboard.md
docs/user_manual/runs.md

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3950

[GLT-3950] updated documentation

---

CHANGELOG.md
add_copyName.md

and remove change file from location where it didn't get picked up

Add change note to changelog

---

.vscode/settings.json
changes/add_medianInsert.md
src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java
src/main/java/ca/on/oicr/gsi/dimsum/data/Sample.java
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3957
I'll have a Cardea PR to match the `Sample` and `CaseLoader` changes shortly

[GLT-3957] handle Median Insert Size metric

---

changes/fix_tglSheet_coverage.md
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/TglTrackingReport.java

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3972

[GLT-3972] fix reversed tumour vs. normal metrics in TGL tracking sheet

---

changes/add_qcNotes.md
package-lock.json
src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java
src/main/java/ca/on/oicr/gsi/dimsum/data/Sample.java
src/main/resources/static/css/output.css
tailwind.config.js
ts/case-report.ts
ts/data/case.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3975
I'll make a Cardea PR to match the model change

[GLT-3975] added QC notes to Case QC Report

---

changes/add_GLT-4003
changes/change_GLT-4003
src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java
src/main/java/ca/on/oicr/gsi/dimsum/data/ProjectSummary.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/ProjectSummaryFilterKey.java
src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/ProjectSummaryFilterTest.java
ts/data/project.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4003

[GLT-4003] added pipeline filter to projects view

---

changes/change_rounding.md
ts/util/metrics.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4028

[GLT-4028] truncate metric values instead of rounding

---

changes/fix_missingMetrics.md
ts/case-report.ts
ts/data/assay.ts
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4032

[GLT-4032] fixed displaying samples with no metrics

---

changes/change_GLT-3979.md
src/main/java/ca/on/oicr/gsi/dimsum/controller/MvcExceptionHandler.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/RestExceptionHandler.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/CustomErrorController.java
src/main/resources/application.yml
src/main/resources/static/css/output.css
src/main/resources/templates/error.html
tailwind.config.js
ts/error.ts
webpack.config.js

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3979
✅ Includes a change file

[GLT-3979] replace default Spring error page with custom error page

---

CHANGELOG.md
add_caseTatWarnings.md
add_gateTat.md

fixed changelog

---

changes/change_caseTatDisplay.md
ts/data/case.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4056

[GLT-4056] improved case-level TAT display

---

changes/add_GLT-4037
ts/case-report.ts
ts/data/case.ts
ts/util/urls.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4037

[GLT-4037] added assay links to cases table and case qc report

---

changes/add_GLT-4034
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java
src/test/java/ca/on/oicr/gsi/dimsum/MockCase.java
src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterTest.java
ts/component/table-components.ts
ts/data/case.ts
ts/data/requisition.ts
ts/util/html-utils.ts

Jira ticket or GitHub issue: 
https://jira.oicr.on.ca/browse/GLT-4034

[GLT-4034] added paused cases handling

---

changes/fix_na_overdue.md
ts/data/case.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4059

[GLT-4059] fixed skipped steps disaplying as behind schedule

---

changes/add_smmips.md
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4055

[GLT-4055] added missing smMIPS metrics

---

changes/change_libQual_skipped.md
pom.xml
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CompletedGate.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/PendingState.java
ts/data/case.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4064

[GLT-4064] support tests with no library qualification step

---

src/main/java/ca/on/oicr/gsi/dimsum/service/NotificationManager.java

With debug level logging enabled, there should now be a message logged for each ticket/run being processed, and at least one message for actions taken on that item. There are a couple warning-level items now too. I think the warnings are all things we'd want to fix, but we'll have to see.

added debug logging to NotificationManager

---

changes/fix_qcInMisoAssay.md
changes/fix_qcInMiso_betweenMetrics.md
ts/data/sample.ts
ts/util/metrics.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4084

[GLT-4084] fixed errors in QC in MISO function

---

changes/fix_notificationAutoclose.md
src/main/java/ca/on/oicr/gsi/dimsum/service/JiraService.java

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4093

[GLT-4093] fixed result limit when retrieving open JIRA issues

---

package-lock.json
package.json
src/main/resources/static/css/output.css
ts/component/dialog.ts
ts/component/table-builder.ts
ts/util/html-utils.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4052
Note the PR target is the other deliverables branch that is approved but not yet merged, and depends on Cardea changes that are also not yet merged/released

[GLT-4052] added input dialog component

---

changes/add_nabuSignoff.md
example-application.properties
package-lock.json
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/CaseRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/data/NabuBulkSignoff.java
src/main/java/ca/on/oicr/gsi/dimsum/data/NabuSignoff.java
src/main/java/ca/on/oicr/gsi/dimsum/service/NabuService.java
src/main/resources/static/css/output.css
ts/case-report.ts
ts/component/dialog.ts
ts/component/dropdown.ts
ts/component/table-builder.ts
ts/data/case.ts
ts/util/requests.ts
ts/util/urls.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-3962
Note the PR target is the other deliverables branch that is approved but not yet merged, and depends on Cardea changes that are also not yet merged/released

[GLT-3962] added Nabu integration to sign off cases from Dimsum

---

changes/fix_zeroMetrics.md
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4094

[GLT-4094] fixed display and highlighting of metrics with value of zero

---

changes/add_nabuSignoff.md
src/main/java/ca/on/oicr/gsi/dimsum/data/CacheUpdatedCase.java
src/main/java/ca/on/oicr/gsi/dimsum/data/CacheUpdatedCaseDeliverable.java
src/main/java/ca/on/oicr/gsi/dimsum/data/CacheUpdatedRelease.java
src/main/java/ca/on/oicr/gsi/dimsum/data/CachedSignoff.java
src/main/java/ca/on/oicr/gsi/dimsum/data/NabuSavedSignoff.java
src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java
src/main/java/ca/on/oicr/gsi/dimsum/service/NabuService.java
ts/component/dialog.ts
ts/data/case.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4053
Note the PR target is the other deliverables branch that is approved but not yet merged, and depends on Cardea changes that are also not yet merged/released

[GLT-4053] cache Nabu sign-offs so they can be displayed immediately

---

changes/change_caseDetails_link.md
ts/data/case.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4104

[GLT-4104] moved the Case Details link

---

changes/change_passedApproved.md
ts/case-report.ts
ts/data/qc-status.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4097

[GLT-4097] changed 'Passed' to 'Approved'

---

changes/add_cfmedips_metrics.md
pom.xml
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4101
Ready for review, but requires a Cardea release and updated dependency version before merging

[GLT-4101] added new metrics for cfMeDIPs

---

changes/fix_cacheError.md
src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java

fixed ConcurrentModificationException when removing cached sign-offs

---

changes/add_csvTsv.md
changes/add_dareInputSheet.md
changes/add_fullDepthSummary.md
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/DownloadRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/Column.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/Report.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/ReportFormat.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/ReportSection.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/DareInputSheet.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/FullDepthSummary.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/shared/CaseSampleRowData.java
ts/data/case.ts

Jira ticket or GitHub issue:
* https://jira.oicr.on.ca/browse/GLT-4109
* https://jira.oicr.on.ca/browse/GLT-4110

[GLT-4109] [GLT-4110] Added reports for data release

---

ts/data/case.ts

fixed bad merge

---

.github/pull_request_template.md

updated PR checklist

---

.vscode/settings.json
changes/change_analysisReviewSkip.md
pom.xml
src/main/java/ca/on/oicr/gsi/dimsum/data/CacheUpdatedCaseDeliverable.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CompletedGate.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/PendingState.java
src/main/java/ca/on/oicr/gsi/dimsum/util/SampleUtils.java
src/test/java/ca/on/oicr/gsi/dimsum/MockCase.java
src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterTest.java
ts/data/case.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4120

[GLT-4120] skip analysis review based on deliverables

---

changes/add_runDetailFilters.md
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/RunRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java
src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterTest.java
ts/component/table-components.ts
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4114

[GLT-4114] added filters to run-library tables on Run Details page

---

changes/add_sampleCopy.md
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4132

[GLT-4132] added Copy Name button for sample/library names

---

changes/add_tatReportDeliverables.md
changes/fix_tatReportCompletions.md
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/MvcUtils.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/CaseTatReport.java
ts/data/case.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4096

[GLT-4096] added separate TAT Report columns for each deliverable type

---

changes/add_pendingReleaseFilter.md
src/main/java/ca/on/oicr/gsi/dimsum/FrontEndConfig.java
src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java
ts/component/table-components.ts
ts/util/site-config.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4115

[GLT-4115] added pending release (deliverable) filter

---

changes/add_tooltip_qcInfo.md
changes/fix_caseQc_analysisReviewNote.md
ts/case-report.ts
ts/data/case.ts
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4135

[GLT-4135] show qc status, user, and notes in tooltips

---

changes/add_multiAssayReq.md
changes/change_caseId_redirect.md
pom.xml
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/CaseController.java
src/main/java/ca/on/oicr/gsi/dimsum/service/NotificationManager.java
src/test/java/ca/on/oicr/gsi/dimsum/service/CaseServiceTest.java
src/test/java/ca/on/oicr/gsi/dimsum/service/NotificationManagerTest.java
ts/case-report.ts
ts/data/case.ts
ts/data/omitted-sample.ts
ts/data/requisition.ts
ts/data/sample.ts
ts/util/metrics.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4098
Requires a Cardea release and dependency bump before merging

[GLT-4098] support multiple assays per requisition

---

changes/add_GLT-4069
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/MvcUtils.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CompletedGate.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/PendingState.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/SampleSort.java
src/main/java/ca/on/oicr/gsi/dimsum/util/DataUtils.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/CaseTatReport.java
src/test/java/ca/on/oicr/gsi/dimsum/MockCase.java
src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterTest.java
src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/SampleSortTest.java
ts/component/date-input.ts
ts/component/table-builder.ts
ts/component/table-components.ts
ts/data/case.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4069

[GLT-4069] added case start and end date filter

---

changes/add_GLT-4133
ts/component/table-builder.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4133

[GLT-4133] added selection count

---

changes/add_reqName_mapping.md
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/RequisitionController.java

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4148

[GLT-4148] added URL mapping for requisition by name

---

changes/add_pendingTransfer.md
changes/add_pendingTransfer_filter.md
pom.xml
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CompletedGate.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/PendingState.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/CaseTatReport.java
src/test/java/ca/on/oicr/gsi/dimsum/MockCase.java
src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterTest.java
ts/data/case.ts
ts/data/qc-status.ts
ts/data/sample.ts
ts/data/test.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4065
Ready for review, but needs a Cardea release and dependency bump before merging

[GLT-4065] added extraction substeps including sample transfer

---

changes/change_qcReport_filename.md
ts/case-report.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4192

[GLT-4192] updated Case QC Report default filename when printing

---

docs/user_manual/cases.md

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4191

[GLT-4194] updated case grouping documentation

---

changes/fix_analysisReview_passFailMetric.md
ts/case-report.ts
ts/data/case.ts
ts/data/sample.ts
ts/util/metrics.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4238

[GLT-4238] fixed display of Analysis Review pass/fail metrics

---

changes/change_omissionsNote.md
docs/user_manual/omissions.md
ts/omissions.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4247

[GLT-4247] updated omitted samples documentation

---

changes/change_dareSheet_excludeFailed.md
docs/user_manual/reports.md
src/main/java/ca/on/oicr/gsi/dimsum/util/DataUtils.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/DareInputSheet.java

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4246

[GLT-4246] excluded failed runlibs from the DARE Input Sheet

---

changes/fix_dv200.md
pom.xml
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4249

[GLT-4249] show DV200 metric values

---

changes/add_GLT-4243
ts/component/text-input.ts

[GLT-4243]added list entry for Dimsum filters

---

changes/add_GLT-4070
docs/user_manual/reports.md
package-lock.json
package.json
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/TatTrendController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/DownloadRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/Report.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/ReportSection.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/CaseTatReport.java
src/main/resources/templates/tat-trend.html
ts/data/case.ts
ts/tat-trend.ts
ts/util/requests.ts
webpack.config.js

[GLT-4070]added TAT trend report

---

changes/change_miso_urls.md
ts/util/urls.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4273

[GLT-4273] updated MISO links

---

changes/change_dare_report_lane.md
changes/change_dare_report_option.md
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/DareInputSheet.java
ts/data/case.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4291

[GLT-4291] DARE Input Sheet improvements

---

changes/fix_date_input.md
ts/component/date-input.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4292

[GLT-4292] fixed date input premature submission

---

changes/fix_jira_maxLength.md
src/main/java/ca/on/oicr/gsi/dimsum/data/Notification.java
src/test/java/ca/on/oicr/gsi/dimsum/data/NotificationTest.java

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4299

[GLT-4299] fixed posting JIRA comments that were too long

---

changes/change_qcReport_sampleMetrics.md
changes/fix_qcReport_missingSamples.md
ts/case-report.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4284

[GLT-4284] fixed missing items on Case QC Report

---

changes/fix_GLT-4301
ts/component/table-builder.ts
ts/util/html-utils.ts

[GLT-4301] fixed QC report table display

---

changes/add_GLT-4271
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java
src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterTest.java
ts/component/table-components.ts

[GLT-4271]add deliverable filter

---

changes/fix_irrelevantSample.md
ts/case-report.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4307

[GLT-4312] fix irrelevant items shown on Case QC Report

---

package-lock.json
pom.xml
src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java
src/main/java/ca/on/oicr/gsi/dimsum/SecurityConfiguration.java
src/main/java/ca/on/oicr/gsi/dimsum/SecurityConfigurationNoAuth.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/MvcExceptionHandler.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/RestExceptionHandler.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/CaseController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/CustomErrorController.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/Report.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/ReportSection.java
src/main/resources/application.yml

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4325

[GLT-4325] Updated to Spring Boot 3.4

---

changes/change_release_qcs.md
changes/change_step_completion.md
docs/user_manual/faq.md
docs/user_manual/qc_dashboard.md
pom.xml
src/main/java/ca/on/oicr/gsi/dimsum/CaseLoader.java
src/main/java/ca/on/oicr/gsi/dimsum/DimSumApplication.java
src/main/java/ca/on/oicr/gsi/dimsum/FrontEndConfig.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/CaseRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/data/CacheUpdatedCaseDeliverable.java
src/main/java/ca/on/oicr/gsi/dimsum/data/CacheUpdatedRelease.java
src/main/java/ca/on/oicr/gsi/dimsum/data/CachedSignoff.java
src/main/java/ca/on/oicr/gsi/dimsum/data/NabuSignoff.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CompletedGate.java
src/main/java/ca/on/oicr/gsi/dimsum/util/DataUtils.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/CaseTatReport.java
src/test/java/ca/on/oicr/gsi/dimsum/MockCase.java
src/test/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseSortTest.java
ts/case-report.ts
ts/component/dialog.ts
ts/data/case.ts
ts/data/qc-status.ts
ts/util/metrics.ts
ts/util/site-config.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4289
Requires Cardea release and version bump before merging

[GLT-4289] switched to new release QC statuses

---

changes/add_fullDepth_collapsedCoverage.md
pom.xml
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4327

[GLT-4327] handle full-depth collapsed coverage metric

---

changes/fix_designFilterOptions.md
src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4329

[GLT-4329] fixed library design filter missing options

---

changes/fix_jira.md
pom.xml
src/test/java/ca/on/oicr/gsi/dimsum/service/JiraServiceTest.java

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4328

[GLT-4328] switch to OICR-GSI fork of JIRA client library

---

changes/change_rbac.md
dev_guide.md
example-application.properties
src/main/java/ca/on/oicr/gsi/dimsum/SecurityConfiguration.java
src/main/java/ca/on/oicr/gsi/dimsum/SecurityUtils.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/SiteConfigController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/CommonModelAttributeProvider.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/CustomErrorController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/HomeController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/internal/AutocompleteRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/internal/CaseRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/internal/DownloadRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/internal/NotificationRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/internal/OmittedSampleRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/internal/ProjectRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/internal/RunRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/internal/SampleRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/internal/TestRestController.java
src/main/resources/templates/layout.html
ts/util/site-config.ts
ts/util/urls.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4315

[GLT-4315] implemented role-based access control

---

ts/case-report.ts
ts/data/assay.ts
ts/data/case.ts
ts/data/data-utils.ts
ts/data/requisition.ts
ts/data/run.ts
ts/data/sample.ts
ts/data/test.ts
ts/util/metrics.ts
ts/util/site-config.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4318

[GLT-4318] adapted TypeScript to external view models

---

changes/add_external_dashboard.md
package-lock.json
src/main/java/ca/on/oicr/gsi/dimsum/FrontEndConfig.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/external/ExternalAutocompleteRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/external/ExternalCaseRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/data/external/ExternalSample.java
src/main/java/ca/on/oicr/gsi/dimsum/data/external/ExternalTest.java
src/main/java/ca/on/oicr/gsi/dimsum/security/SecurityConfiguration.java
src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java
src/main/resources/static/css/output.css
src/main/resources/templates/layout.html
ts/component/legend.ts
ts/component/table-builder.ts
ts/component/table-components.ts
ts/data/case.ts
ts/data/omitted-sample.ts
ts/data/project-summary-row.ts
ts/data/project.ts
ts/data/qc-status.ts
ts/data/run.ts
ts/util/html-utils.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4319

[GLT-4319] adapted main dashboard for external users

---

changes/add_external_detailPages.md
src/main/java/ca/on/oicr/gsi/dimsum/controller/UnauthorizedException.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/DonorController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/ProjectController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/RequisitionController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/external/ExternalSampleRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/external/ExternalTestRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/data/external/ExternalTest.java
src/main/java/ca/on/oicr/gsi/dimsum/data/external/ExternalTestTableView.java
src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseSort.java
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/TestTableViewSort.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/shared/CaseSampleRowData.java
src/main/resources/templates/detail.html
src/test/java/ca/on/oicr/gsi/dimsum/service/CaseServiceTest.java
ts/component/table-builder.ts
ts/data/case.ts
ts/data/notification.ts
ts/data/omitted-sample.ts
ts/data/project.ts
ts/data/run.ts
ts/data/sample.ts
ts/data/test.ts
ts/details.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4320

[GLT-4320] adapted detail pages for external users

---

changes/change_seqStatus.md
ts/data/case.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4061

[GLT-4061] show sequencing status while running

---

add_external_projectDetails.md
src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/ProjectController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/common/CommonProjectRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/controller/rest/internal/ProjectRestController.java
src/main/java/ca/on/oicr/gsi/dimsum/data/ProjectSummaryField.java
src/main/java/ca/on/oicr/gsi/dimsum/data/ProjectSummaryRow.java
src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java
src/main/resources/templates/project-detail.html
ts/project-details.ts
ts/util/urls.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4322

[GLT-4322] adapted Project Details page for external users

---

changes/fix_noMetric.md
ts/util/site-config.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4340

[GLT-4340] fixed metrics undefined js error

---

ts/details.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4323
Didn't add a changelog entry as there's already a pending entry about adapting the Case Details page

[GLT-4323] removed QC Report link from external view

---

changes/change_caseToTest.md
src/main/resources/templates/tat-trend.html
ts/tat-trend.ts

[GLT-4344] changed case count/full case to test count/full test

---

changes/fix_openSAMLInPom.md
pom.xml

fixed OpenSAML dependency in pom.xml

---

src/main/java/ca/on/oicr/gsi/dimsum/controller/mvc/CaseController.java
src/main/java/ca/on/oicr/gsi/dimsum/security/SecurityConfiguration.java

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4338

[GLT-4338] whitelist specific pages for external user access

---

docs/README.md

Jira ticket or GitHub issue:
- [ n/a ] Includes a change file
- [ n/a ] Updated tests (or n/a)
- [ n/a ] Discussed with CGI (or n/a; see release procedure on wiki for applicability)

Fix URL to docs

---

changes/fix_qcInMisoRounding.md
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4357

[GLT-4357] fixed QC in MISO using display values

---

changes/fix_libraryDesignFilter.md
pom.xml
src/main/java/ca/on/oicr/gsi/dimsum/service/filtering/CaseFilterKey.java

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4349
Ready for review, but requires Cardea release and version bump before merging

[GLT-4349] fixed library design filter for library qualification

---

changes/fix_tatTrend_receiptDays.md
ts/tat-trend.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4375

[GLT-4375] fixed TAT Trend always showing zero receipt days

---

changes/change_donorAssayReport_sorting.md
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/DonorAssayReport.java

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4407

[GLT-4407] sort Donor Assay Report

---

changes/fix_removeFilter.md
ts/component/table-builder.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4406

[GLT-4406] fixed removing table filters from URL

---

changes/change_tatCategories.md
src/main/java/ca/on/oicr/gsi/dimsum/FrontEndConfig.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/ReportSection.java
src/main/java/ca/on/oicr/gsi/dimsum/util/reporting/reports/CaseTatReport.java
src/main/resources/templates/tat-trend.html
ts/tat-trend.ts
ts/util/site-config.ts
ts/util/urls.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4422

[GLT-4422] include all deliverable categories in TAT reporting

---

changes/fix_external_passedOnly.md
src/main/java/ca/on/oicr/gsi/dimsum/data/external/ExternalTest.java
src/main/java/ca/on/oicr/gsi/dimsum/service/CaseService.java
src/main/java/ca/on/oicr/gsi/dimsum/util/DataUtils.java

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4658

[GLT-4658] fixed external view to only show samples after passing QC

---

changes/fix_qcInMiso_metrics.md
ts/data/sample.ts

Jira ticket or GitHub issue: https://jira.oicr.on.ca/browse/GLT-4668

[GLT-4668] fixed missing metric values in QC in MISO request
